### ISSUE TITLE
Pebble variants craft into stones incorrectly

### ISSUE THREAD

**Issue by Partonetrain** [polyvalord/extcaves#1]
Normal stone pebbles craft into all three stone variants (but since lavastone is the first recipe, that is what is crafted).

![image](https://user-images.githubusercontent.com/19861808/64477405-d6a95d00-d160-11e9-8c35-7a5834cbf79d.png)

Limestone Pebbles and Lavastone pebbles cannot be crafted into their full blocks and have no use.

**Comment by polyvalord** [comment]
Thanks for the feedback I will correct this for the next version

**Comment by Partonetrain** [comment]
Was fixed in latest update, thanks
