### ISSUE TITLE
Broken stone

### ISSUE THREAD

**Issue by SpGilbert** [polyvalord/extcaves#11]
There is a broken kind of vanilla stone the extended caves makes and you cant pick it up in creative and it messes up the one probe and its an error block it also spawns when stone varients in the mod is turned off and it looks like vanilla stone.

**Comment by polyvalord** [comment]
It's stone where only stone speleothems can spawn on.
It's glitchy and someone on the mod page provided a great solution I'm probably going to use.

**Comment by polyvalord** [comment]
Fixed in 1.16 version
