### ISSUE TITLE
[Idea] Killer Bunny

### ISSUE THREAD

**Issue by MeinKraft** [polyvalord/extcaves#12]
So this might not make a lot of sense unless you've seen the film Monty Python's Holy Grail

So in a cave lives a killer rabbit.  Could you implement a chance for Minecraft's Killer Rabbit to spawn in caves. On/Off by a config option, Spawn Chance by config

it was just a fun idea

**Comment by polyvalord** [comment]
I don't plan on adding any mobs in this mod.

By the way, I think killer bunnies already exist in minecraft maybe I'm wrong.
