### ISSUE TITLE
Allow Stalagmites, Stalactites, & Crystals to be Waterlogged

### ISSUE THREAD

**Issue by WenXin20** [polyvalord/extcaves#4]
Forge v28.1.44
Extended Caves v1.2

Currently, the Crystals, Rock Piles, Pebbles, Stalagmites, & Stalactites cannot be waterlogged. Allowing this would add more immersion to the game.
![2019-10-11_22 24 24](https://user-images.githubusercontent.com/12000593/66694169-5782d980-ec76-11e9-98c5-37eb85b7978c.png)

**Comment by polyvalord** [comment]
Thanks.
Firstly I want to be sure about the models before making them waterloggable but I will take this in consideration in the future.

**Comment by polyvalord** [comment]
In 1.16 all blocks from this mod are waterloggable !
