### ISSUE TITLE
Stalagmites difficult mob pathing

### ISSUE THREAD

**Issue by vicitafirea** [polyvalord/extcaves#5]
https://imgur.com/a/0K4jMw6
Three screenshots showing mobs trying to pass through the stalagmites.

They can cross small stalagmites due to not being cubes but if a stalagmite is directly between the player and the mob they can't go through it and they never try to jump above it.

Tall stalagmites will also block the mobs' way to reach the player. they sometimes try to jump but they don't try to surround it.

As a suggestion, the small stalagmites could be non-solid blocks and tall stalagmites be solid blocks in a way mobs recognize they can't cross them. The model of the latter one could also be tweaked to be thicker

**Comment by polyvalord** [comment]
Thanks for your screenshots and feedback !
Beside your suggestions I should try to make the hitboxes matching perfectly the models - it could solve the problem too.
Not very sure but I will tweak them.

**Comment by polyvalord** [comment]
Finally found a fix for this, will be done for 1.16
