### ISSUE TITLE
Suggestion for dungeons

### ISSUE THREAD

**Issue by vicitafirea** [polyvalord/extcaves#6]
![2019-10-14_11 34 59](https://user-images.githubusercontent.com/55768134/66962997-eada5700-f048-11e9-922b-8735b3650d7b.png)
![2019-10-14_11 36 05](https://user-images.githubusercontent.com/55768134/66962998-eb72ed80-f048-11e9-9283-70259034c021.png)
![2019-10-14_13 07 50](https://user-images.githubusercontent.com/55768134/66962999-eb72ed80-f048-11e9-8865-af0de064144e.png)

I've installed recently the mod "Yung's Better Caves" and altough it helped a lot about my previous issue of speleothems blocking the path of mobs (because these spawn scattered a lot more), it also made the dungeons spawn half above the air more often.
I suggest changing the worldgen to check if the floor area (of the potential dungeon) is entirely solid.

**Comment by slard3** [comment]
Another suggestion: there could be another check before generation to see if there's a dungeon/cabin nearby. Simply to make structures don't spawn so attached (a lot of times I've seen a cabin and dungeon very near to each other). Adding this to the config would make it even better.

**Comment by polyvalord** [comment]
The floor area under structures was checked originally. But it was making the structures insanely rares even with a high spawn rate.
I'll try to answer those suggestions.

**Comment by polyvalord** [comment]
Since the last version cabins and dungeons spawn properly !
But they still can generate too close aww.
