### ISSUE TITLE
Graphics of Upward big stalagmites are bugged with shaders

### ISSUE THREAD

**Issue by SatDog92** [polyvalord/extcaves#7]
I want to notice that i use the Preview version of Optifine which is compatible with Forge but not fully stable. Mod works fine except from the fact that the graphics of upward big stalagmites is bugged: the tip fades in black as if there was permanent shadow there.

I don't know if this is an Optifine problem or a mod one, but i felt it was appropriate to report this graphical bug.

**Comment by polyvalord** [comment]
Fixed since 1.3.3 !
