### ISSUE TITLE
please port to 1.12.2

### ISSUE THREAD

**Issue by 000THEALPHA000** [polyvalord/extcaves#9]
hi could you please port to 1.12.2 as that is where the large majority of mods are.
like mocreatures dynamic trees biomes o plenty and many more
 thanks alot keep up the good work

**Comment by polyvalord** [comment]
I'm not against a 1.12.2 version but I don't want to make it myself because I started modding with the 1.14 version which is way different and I don't want to backport features.

**Comment by polyvalord** [comment]
No pre 1.14 version planned -

**Comment by 000THEALPHA000** [comment]
the problem is that 1.12.2 host 90% of all the good mods that version had
the largest selection of mods so i like your mod sadly i don't want to
throw away like 30 other mods that aren't updated and seemingly will never
be like mo creatures or dragonmounts 2

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by polyvalord** [comment]
I don't have the time to do it.
If you find someone willing to port it why not.
